[TH2-4276] basic and extended cradle modules
th2-net/cradleapi pull request #187
Opened 2022-11-30 09:00 UTC by Xanclry

2022-12-01 06:31 UTC, Nikita-Smirnov-Exactpro requested changes

2022-12-01 06:31 UTC, Nikita-Smirnov-Exactpro commented on basic-cradle-manager/src/main/java/com/exactpro/cradle/module/DummyCradleManager.java
> + * Copyright 2020-2022 Exactpro (Exactpro Systems Limited)
```suggestion
 * Copyright 2022 Exactpro (Exactpro Systems Limited)
```
The first date should be year of file made

2022-12-01 06:31 UTC, Nikita-Smirnov-Exactpro commented on cradle-manager-api/src/main/java/com/exactpro/cradle/module/CradleManagerModule.java
> +            throw new IllegalArgumentException("CradleManager doesn't support " + aClass);
```suggestion
            throw new IllegalArgumentException("CradleManager doesn't support the " + aClass + " configuration class");
```

2022-12-01 06:31 UTC, Nikita-Smirnov-Exactpro commented on cradle-manager-api/src/main/java/com/exactpro/cradle/module/CradleManagerModule.java
> +    public void initConfigurationProvider(ConfigurationProvider configurationProvider) {
Could we avoid init method by passing provider into methods or constructor?

2022-12-01 06:31 UTC, Nikita-Smirnov-Exactpro commented on cradle-manager-api/src/main/java/com/exactpro/cradle/config/CradleConfiguration.java
> +@Deprecated(message = "Please use CradleConfidentialConfiguration and CradleNonConfidentialConfiguration")
Could we refactor as described in message?

2022-12-01 06:31 UTC, Nikita-Smirnov-Exactpro commented on basic-cradle-manager/src/main/java/com/exactpro/cradle/module/DummyCradleManager.java
> +public class DummyCradleManager extends CradleManager {
If it is base implementation provided configuration then rename to BaseCradleManager otherwise please explain the goal of this class

2022-12-01 06:54 UTC, georgiano requested changes
So, are you making changes into obsolete version?
master is for 2.21 version that is no more maintained.

current active branches are **dev-version-3.2** & **dev-version-5**

2022-12-02 09:03 UTC, Nikita-Smirnov-Exactpro requested changes

2022-12-02 09:03 UTC, Nikita-Smirnov-Exactpro commented on cradle-manager-api/src/main/java/com/exactpro/cradle/module/CradleManagerModule.java
> +        if (aClass.equals(CradleConfidentialConfiguration.class)) {
Could you please Objects.equals method to avoid NPE

2022-12-02 09:03 UTC, Nikita-Smirnov-Exactpro commented on cradle-manager-api/src/main/java/com/exactpro/cradle/module/CradleManagerModule.java
> +    public void initConfigurations(CradleConfidentialConfiguration confidentialConfiguration, CradleNonConfidentialConfiguration nonConfidentialConfiguration) {
Could we move the logic of this method into CassandraCradleManager constructor and remove the method?

2022-12-02 09:03 UTC, Nikita-Smirnov-Exactpro commented on full-cradle-manager/src/main/java/com/exactpro/cradle/module/FullCradleManagerFactoryImpl.java
>              manager.init(
Could we avoid init methods

2022-12-05 08:16 UTC, Nikita-Smirnov-Exactpro requested changes

2022-12-05 08:16 UTC, Nikita-Smirnov-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/CradleManager.java
>  {
The CradleManagerModule class looks like as redundant, maybe merge CradleManagerModule into CradleManager

2022-12-05 08:16 UTC, Nikita-Smirnov-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/DefaultCradleManager.java
> +	}
Why do we need default constructor?

2022-12-05 08:16 UTC, Nikita-Smirnov-Exactpro commented
>

2022-12-05 08:22 UTC, Nikita-Smirnov-Exactpro commented
> So, are you making changes into obsolete version? master is for 2.21 version that is no more maintained.
> 
> current active branches are **dev-version-3.2** & **dev-version-5**

We are going to implement modules for **dev-version-3.1** because current th2 components refer to in in master branches and implement in **dev-version-5**

2024-03-06 14:34 UTC, closed without merging