Th2 1791 getMessages - iterate over batches directly
th2-net/cradleapi pull request #22
Opened 2021-04-20 08:16 UTC by MrJonniK

2021-04-20 08:36 UTC, MrJonniK commented
Limit from filter doesn't work

2021-04-20 08:41 UTC, Vladimir-Panarin-Exactpro requested changes
To sum up, replace all "messages batches" with "message batches".

2021-04-20 08:41 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/iterators/StoredMessageBatchIterator.java
> +			throw new IOException("Error occurs while getting StoredMessageBatch",e);
`Error occurred while converting entity to StoredMessageBatch`

2021-04-20 08:41 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/CradleStorage.java
> +	 * Allows to enumerate stored messages batches, optionally filtering them by given conditions
"Allows to enumerate stored message batches"

2021-04-20 08:41 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/CradleStorage.java
> +		logger.debug("Prepared iterator for messages batches filtered by {}", filter);
"Prepared iterator for message batches filtered by {}"

2021-04-20 08:41 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/CradleStorage.java
> +	 * Allows to asynchronously obtain iterable object to enumerate stored messages batches, optionally filtering them by given conditions
"to enumerate stored message batches"

2021-04-20 09:35 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/iterators/StoredMessageBatchIterator.java
> +	private long returnedEtities;
`returnedEntities`

2021-04-30 11:47 UTC, merged

2021-05-04 16:35 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/dao/messages/DetailedMessageBatchEntity.java
> +	public StoredMessageBatch toStoredMessageBatch(StoredMessageBatch messageBatch)
Add a comment why you need the input parameter. This is because it should be created by CradleObjectsFactory, if I'm not mistaken.

2021-05-04 16:35 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/CradleStorage.java
> +	 * @param filter defines conditions to filter message batches by. Use null is no filtering is needed
"Use null is no filtering is needed" > "Use null if no filtering is needed"

2021-05-04 16:35 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/CradleStorage.java
> +	 * @param filter defines conditions to filter message batches by. Use null is no filtering is needed
"Use null is no filtering is needed" > "Use null if no filtering is needed"