TH2-2036. Message filtering by timestamp is inefficient
th2-net/cradleapi pull request #41
Opened 2021-08-06 06:56 UTC by MrJonniK

2021-08-06 17:02 UTC, Vladimir-Panarin-Exactpro requested changes

2021-08-06 17:02 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/dao/messages/MessageBatchQueryProvider.java
> +				throw new CradleStorageException("Error getting message batch index for timestamp 'To'", e);
throw new CradleStorageException("Error while getting message batch index for timestamp 'To'="+ts, e);

2021-08-06 17:02 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/dao/messages/MessageBatchQueryProvider.java
> +				builder = builder.setLong(LEFT_MESSAGE_INDEX, leftBatchIndex);
There seem to be a conflict if someone defines both timestampFrom and index in the filter. Better use different placeholder name for index obtained for timestampFrom.

2021-08-09 07:41 UTC, Vladimir-Panarin-Exactpro approved these changes

2021-08-09 07:49 UTC, MrJonniK commented
This commit doesn't work if the filter contains index and from/to constraints. Cassandra throw the next exception `More than one restriction was found for the start bound  on message_index`

2021-08-10 06:39 UTC, Vladimir-Panarin-Exactpro requested changes

2021-08-10 06:39 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/dao/messages/MessageBatchQueryProvider.java
> +			if (filter.getLimit() > 0 && (op == ComparisonOperation.LESS || op == ComparisonOperation.LESS_OR_EQUALS))
`else if`

2021-08-10 07:47 UTC, MrJonniK commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/dao/messages/MessageBatchQueryProvider.java
> +			if (filter.getLimit() > 0 && (op == ComparisonOperation.LESS || op == ComparisonOperation.LESS_OR_EQUALS))
But if above contains return statement

2021-08-10 08:14 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/dao/messages/MessageBatchQueryProvider.java
> +			if (filter.getLimit() > 0 && (op == ComparisonOperation.LESS || op == ComparisonOperation.LESS_OR_EQUALS))
Ok.

2021-08-10 08:16 UTC, Vladimir-Panarin-Exactpro approved these changes

2021-08-10 08:27 UTC, merged