TH2-2401. Need to change the storage of test events and store their body along with metadata
th2-net/cradleapi pull request #48
Opened 2021-09-20 11:48 UTC by MrJonniK

2021-09-20 12:02 UTC, MrJonniK commented
Abaddoned

2021-09-21 11:05 UTC, Vladimir-Panarin-Exactpro requested changes

2021-09-21 11:05 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/TablesCreator.java
>  		createTestEventsTable();
Remove creation of unused fields here.

2021-09-21 11:05 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/dao/testevents/TestEventEntity.java
> +		this.parentId = parentId == null ? ROOT_EVENT_PARENT_ID : parentId;
Use null when converting entity into StoredTestEvent.

2021-09-22 08:00 UTC, Vladimir-Panarin-Exactpro requested changes

2021-09-22 08:18 UTC, Vladimir-Panarin-Exactpro approved these changes

2021-09-22 08:55 UTC, Vladimir-Panarin-Exactpro requested changes

2021-09-22 08:55 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/dao/testevents/TestEventEntity.java
> +			setStartDate(null);
set endDate/endTime here!

2021-12-24 10:42 UTC, closed without merging

2021-12-24 10:45 UTC, MrJonniK commented
Version 3 of Cradle API is being developed in branch https://github.com/th2-net/cradleapi/tree/ver_3_1_dev