TH2-2216. Added: check for message date when added to message batch, check for book id for sub events, checks for components of StoredMessageId and StoredTestEventId.
th2-net/cradleapi pull request #66
Opened 2021-12-22 07:03 UTC by MrJonniK

2021-12-23 12:12 UTC, Vladimir-Panarin-Exactpro requested changes

2021-12-23 12:12 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/testevents/TestEventSingleToStore.java
> +						messageBookId + "' that different from the current event book id '" + eventBookId + "'");
"Book of message is (" + messageBookId + ") differs from the event book (" + eventBookId + ")"

2021-12-23 12:12 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/utils/MessageUtils.java
> +		if (StringUtils.isEmpty(message.getSessionAlias()) )
Extra space added?

2021-12-23 12:12 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/utils/MessageUtils.java
> +		if (message.getTimestamp().isAfter(now))
This check may lead to problem when validation is done not before adding a message. Is it possible?

2021-12-23 12:12 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/utils/MessageUtils.java
> +							"' It can not be greater than current '" + TimeUtils.toLocalTimestamp(now) + "'");
"can not" > "cannot"

2021-12-23 13:12 UTC, MrJonniK commented on cradle-core/src/main/java/com/exactpro/cradle/utils/MessageUtils.java
> +		if (StringUtils.isEmpty(message.getSessionAlias()) )
This is my mistake

2021-12-24 08:18 UTC, Vladimir-Panarin-Exactpro requested changes

2021-12-24 08:18 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/test/java/com/exactpro/cradle/messages/MessageBatchToStoreTest.java
> +					{builder.bookId(book).sessionAlias("").direction(null).timestamp(null)},               		 	 //Empty session are set
"are set" > "is set".

2021-12-24 08:18 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/messages/MessageBatchToStore.java
> +							"' It cannot be greater than current '" + TimeUtils.toLocalTimestamp(now) + "'");
"Message timestamp is " + TimeUtils.toLocalTimestamp(message.getTimestamp()) +
		"' It cannot be greater than current timestamp (" + TimeUtils.toLocalTimestamp(now) + ")");

2021-12-24 08:18 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/testevents/TestEventSingleToStore.java
> +						messageBookId + ") differs from the event book (" + eventBookId + ")");
throw new CradleStorageException("Book of message (" +
						messageBookId + ") differs from the event book (" + eventBookId + ")");

2021-12-24 09:51 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/messages/MessageBatchToStore.java
> +							") It cannot be greater than current timestamp (" + TimeUtils.toLocalTimestamp(now) + ")");
"Message timestamp (" + TimeUtils.toLocalTimestamp(message.getTimestamp()) +
							") is greater than current timestamp (" + TimeUtils.toLocalTimestamp(now) + ")");

2021-12-24 10:14 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/utils/TestEventUtils.java
> +							"' It can not be greater than current '" + TimeUtils.toLocalTimestamp(now) + "'");
"Event start timestamp (" + TimeUtils.toLocalTimestamp(event.getStartTimestamp()) +
							") is greater than current timestamp (" + TimeUtils.toLocalTimestamp(now) + ")");

2021-12-24 10:25 UTC, Vladimir-Panarin-Exactpro approved these changes

2021-12-24 10:31 UTC, merged