Th2 2611. Implemented retries for "select" queries
th2-net/cradleapi pull request #70
Opened 2022-01-11 11:31 UTC by MrJonniK

2022-01-11 12:05 UTC, Vladimir-Panarin-Exactpro requested changes

2022-01-11 12:05 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/retries/RetryUtils.java
> +	public static List<List<String>> applyPolicyVerdict(List<String> ids, SelectExecutionVerdict policyVerdict)
This method looks like not needed anymore as we don't query multiple IDs.

2022-01-11 12:05 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/retries/SelectExecutionPolicy.java
> +	SelectExecutionVerdict onError(Collection<String> ids, String queryInfo, Throwable cause, int retryCount) throws CannotRetryException;
This method looks like not needed anymore as we don't query multiple IDs.

2022-01-11 12:34 UTC, MrJonniK commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/CassandraCradleStorage.java
> +			eventsWorker = new EventsWorker(settings, ops, composingService, bpc, selectExecutor, writeAttrs, readAttrs);
I agree

2022-01-13 09:34 UTC, Vladimir-Panarin-Exactpro requested changes
+ it is better to update copyright in "new" classes to have 2021-2022.

2022-01-13 09:34 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/workers/EventsWorker.java
> +				String.format("getting test event by id '%s'", id))
"get", not "getting"? See how it will look in logs.

2022-01-13 09:34 UTC, Vladimir-Panarin-Exactpro commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/workers/MessagesWorker.java
> +		String queryInfo = format("getting nearest time and sequence before %s for page '%s'",
"get", not "getting"?

2022-01-14 15:33 UTC, Vladimir-Panarin-Exactpro approved these changes

2022-01-14 15:44 UTC, merged