[TH2-2975] Escape restricted characters in Book's keyspace name
th2-net/cradleapi pull request #75
Opened 2022-01-19 16:56 UTC by std000

2022-01-20 07:32 UTC, MrJonniK commented on cradle-core/src/main/java/com/exactpro/cradle/CradleStorage.java
> +		if (book.getFirstPageName() == null || !BOOK_PAGE_NAME_PATTERN.matcher(book.getFirstPageName()).matches()) {
why is the page name so strictly limited?

2022-01-20 11:55 UTC, Vladimir-Panarin-Exactpro requested changes

2022-01-20 11:55 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/CradleStorage.java
> +				throw new CradleStorageException("Invalid page name. Alphanumeric characters and underscore are allowed.");
Show page name here.

2022-01-20 11:55 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/CradleStorage.java
> +			if (page.getName() == null || !BOOK_PAGE_NAME_PATTERN.matcher(page.getName()).matches()) {
Move this to separate method `validatePageName(String name)`?

2022-01-20 11:55 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/CradleStorage.java
> +		if (book.getFirstPageName() == null || !BOOK_PAGE_NAME_PATTERN.matcher(book.getFirstPageName()).matches()) {
Use new `validatePageName(String name)` method here.

2022-01-21 16:15 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/test/java/com/exactpro/cradle/CradleStorageTest.java
> +	@Test(expectedExceptions = {CradleStorageException.class}, expectedExceptionsMessageRegExp = "Invalid book name.*")
I propose to move all names-related tests to separate class.

2022-01-21 16:15 UTC, Vladimir-Panarin-Exactpro approved these changes
Despite of proposal to move name-related to tests to separate class I don't have objections.

2022-01-21 16:30 UTC, merged