TH2-3139. Added check for timestamp of message when added to batch.
th2-net/cradleapi pull request #81
Opened 2022-02-10 14:30 UTC by MrJonniK

Added ability to create `StoredMessageBatch` without message checks when reading from db

2022-02-10 15:23 UTC, Vladimir-Panarin-Exactpro requested changes

2022-02-10 15:23 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/messages/StoredMessageBatch.java
> +						"Message timestamp should be greater than last message timestamp in batch '" + lastMsg.getTimestamp()
"should be greater than" > "should be not less than"

2022-02-10 15:23 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/messages/StoredMessageBatch.java
>  		//first message in the batch. Need to fill it by services
What "services"? Looks like this should be removed like in Cradle API 2.

2022-02-10 15:23 UTC, Vladimir-Panarin-Exactpro commented on cradle-core/src/main/java/com/exactpro/cradle/messages/StoredMessageBatch.java
>  		if (messages.isEmpty()) {
If first message is too large to fit in batch, it will be rejected but `batchSize` becomes assigned like message was added.

2022-02-15 09:36 UTC, std000 approved these changes

2022-02-15 10:47 UTC, Vladimir-Panarin-Exactpro approved these changes

2022-02-15 10:47 UTC, merged