TH2-3266. Change retry logic for checking keyspace readiness
th2-net/cradleapi pull request #86
Opened 2022-02-25 10:25 UTC by Zurab-Mujirishvili

## Functionality

Cradle Cassandra will now check for keyspace readiness every fixed time interval (currently 500 ms), for a maximum of **TIMEOUT** milliseconds, where **TIMEOUT** is the timeout specified in `CassandraStorageSettings`.

If the specified timeout is shorter than the **retry interval**, exactly one attempt will be made to wait. The first wait will **always** last for the fixed **retry interval**.

## Testing

No new tests were added for this functionality.

2022-02-25 11:24 UTC, georgiano approved these changes

2022-02-25 11:25 UTC, MrJonniK requested changes

2022-02-25 11:25 UTC, MrJonniK commented on cradle-cassandra/src/main/java/com/exactpro/cradle/cassandra/keyspaces/KeyspaceCreator.java
> +					"Keyspace '" + keyspace + "' unavailable after " + settings.getTimeout() + "ms of awaiting");
When `settings.getTimeout()` is less then `KEYSPACE_WAIT_TIMEOUT` you will wait `KEYSPACE_WAIT_TIMEOUT` ms, not `settings.getTimeout()` ms as you report in this message

2022-02-25 11:28 UTC, MrJonniK approved these changes

2022-02-28 09:05 UTC, Vladimir-Panarin-Exactpro approved these changes

2022-03-01 07:59 UTC, merged